### ISSUE TITLE
Can't upload mbtile over 100mb

### ISSUE THREAD

**Issue by monepa** [bmcbride/leaflet-mbtiles#2]
Hi.. i can't upload local mbtile file over 100mb..  can it set to over 100mb or more? thanks

**Comment by bmcbride** [comment]
Not likely since it's a limitation of sql.js needing to read the entire file in memory. See here for more info: https://github.com/sql-js/sql.js/wiki/FAQ#why-do-database-files-in-sqljs-take-so-much-more-memory-than-other-native-sqlite-solutions.
